//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netplait.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class CSS : global::System.Configuration.ApplicationSettingsBase {
        
        private static CSS defaultInstance = ((CSS)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CSS())));
        
        public static CSS Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Caret {
            get {
                return ((global::System.Drawing.Color)(this["Caret"]));
            }
            set {
                this["Caret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color Defaulttext {
            get {
                return ((global::System.Drawing.Color)(this["Defaulttext"]));
            }
            set {
                this["Defaulttext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultBold {
            get {
                return ((bool)(this["DefaultBold"]));
            }
            set {
                this["DefaultBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultItalic {
            get {
                return ((bool)(this["DefaultItalic"]));
            }
            set {
                this["DefaultItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("162, 201, 150")]
        public global::System.Drawing.Color Attribute {
            get {
                return ((global::System.Drawing.Color)(this["Attribute"]));
            }
            set {
                this["Attribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AttributeBold {
            get {
                return ((bool)(this["AttributeBold"]));
            }
            set {
                this["AttributeBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AttributeItalic {
            get {
                return ((bool)(this["AttributeItalic"]));
            }
            set {
                this["AttributeItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 161, 195")]
        public global::System.Drawing.Color Class {
            get {
                return ((global::System.Drawing.Color)(this["Class"]));
            }
            set {
                this["Class"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClassBold {
            get {
                return ((bool)(this["ClassBold"]));
            }
            set {
                this["ClassBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClassItalic {
            get {
                return ((bool)(this["ClassItalic"]));
            }
            set {
                this["ClassItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color Comment {
            get {
                return ((global::System.Drawing.Color)(this["Comment"]));
            }
            set {
                this["Comment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentBold {
            get {
                return ((bool)(this["CommentBold"]));
            }
            set {
                this["CommentBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentItalic {
            get {
                return ((bool)(this["CommentItalic"]));
            }
            set {
                this["CommentItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("129, 160, 227")]
        public global::System.Drawing.Color Directive {
            get {
                return ((global::System.Drawing.Color)(this["Directive"]));
            }
            set {
                this["Directive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DirectiveBold {
            get {
                return ((bool)(this["DirectiveBold"]));
            }
            set {
                this["DirectiveBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DirectiveItalic {
            get {
                return ((bool)(this["DirectiveItalic"]));
            }
            set {
                this["DirectiveItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("162, 201, 150")]
        public global::System.Drawing.Color DoubleString {
            get {
                return ((global::System.Drawing.Color)(this["DoubleString"]));
            }
            set {
                this["DoubleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoubleStringBold {
            get {
                return ((bool)(this["DoubleStringBold"]));
            }
            set {
                this["DoubleStringBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoubleStringItalic {
            get {
                return ((bool)(this["DoubleStringItalic"]));
            }
            set {
                this["DoubleStringItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 161, 195")]
        public global::System.Drawing.Color ExtendedIdentifier {
            get {
                return ((global::System.Drawing.Color)(this["ExtendedIdentifier"]));
            }
            set {
                this["ExtendedIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtendedIdentifierBold {
            get {
                return ((bool)(this["ExtendedIdentifierBold"]));
            }
            set {
                this["ExtendedIdentifierBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtendedIdentifierItalic {
            get {
                return ((bool)(this["ExtendedIdentifierItalic"]));
            }
            set {
                this["ExtendedIdentifierItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 161, 195")]
        public global::System.Drawing.Color ExtendedPseudoClass {
            get {
                return ((global::System.Drawing.Color)(this["ExtendedPseudoClass"]));
            }
            set {
                this["ExtendedPseudoClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtendedPseudoClassBold {
            get {
                return ((bool)(this["ExtendedPseudoClassBold"]));
            }
            set {
                this["ExtendedPseudoClassBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtendedPseudoClassItalic {
            get {
                return ((bool)(this["ExtendedPseudoClassItalic"]));
            }
            set {
                this["ExtendedPseudoClassItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 161, 195")]
        public global::System.Drawing.Color ExtendedPseudoElement {
            get {
                return ((global::System.Drawing.Color)(this["ExtendedPseudoElement"]));
            }
            set {
                this["ExtendedPseudoElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtendedPseudoElementBold {
            get {
                return ((bool)(this["ExtendedPseudoElementBold"]));
            }
            set {
                this["ExtendedPseudoElementBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtendedPseudoElementItalic {
            get {
                return ((bool)(this["ExtendedPseudoElementItalic"]));
            }
            set {
                this["ExtendedPseudoElementItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 161, 195")]
        public global::System.Drawing.Color Id {
            get {
                return ((global::System.Drawing.Color)(this["Id"]));
            }
            set {
                this["Id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdBold {
            get {
                return ((bool)(this["IdBold"]));
            }
            set {
                this["IdBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdItalic {
            get {
                return ((bool)(this["IdItalic"]));
            }
            set {
                this["IdItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("121, 175, 219")]
        public global::System.Drawing.Color Identifier {
            get {
                return ((global::System.Drawing.Color)(this["Identifier"]));
            }
            set {
                this["Identifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdentifierBold {
            get {
                return ((bool)(this["IdentifierBold"]));
            }
            set {
                this["IdentifierBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdentifierItalic {
            get {
                return ((bool)(this["IdentifierItalic"]));
            }
            set {
                this["IdentifierItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("249, 176, 99")]
        public global::System.Drawing.Color Identifier2 {
            get {
                return ((global::System.Drawing.Color)(this["Identifier2"]));
            }
            set {
                this["Identifier2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Identifier2Bold {
            get {
                return ((bool)(this["Identifier2Bold"]));
            }
            set {
                this["Identifier2Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Identifier2Italic {
            get {
                return ((bool)(this["Identifier2Italic"]));
            }
            set {
                this["Identifier2Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 161, 195")]
        public global::System.Drawing.Color Identifier3 {
            get {
                return ((global::System.Drawing.Color)(this["Identifier3"]));
            }
            set {
                this["Identifier3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Identifier3Bold {
            get {
                return ((bool)(this["Identifier3Bold"]));
            }
            set {
                this["Identifier3Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Identifier3Italic {
            get {
                return ((bool)(this["Identifier3Italic"]));
            }
            set {
                this["Identifier3Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("236, 98, 104")]
        public global::System.Drawing.Color Important {
            get {
                return ((global::System.Drawing.Color)(this["Important"]));
            }
            set {
                this["Important"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportantBold {
            get {
                return ((bool)(this["ImportantBold"]));
            }
            set {
                this["ImportantBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportantItalic {
            get {
                return ((bool)(this["ImportantItalic"]));
            }
            set {
                this["ImportantItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 120, 195")]
        public global::System.Drawing.Color Media {
            get {
                return ((global::System.Drawing.Color)(this["Media"]));
            }
            set {
                this["Media"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaBold {
            get {
                return ((bool)(this["MediaBold"]));
            }
            set {
                this["MediaBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaItalic {
            get {
                return ((bool)(this["MediaItalic"]));
            }
            set {
                this["MediaItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("129, 160, 227")]
        public global::System.Drawing.Color Operator {
            get {
                return ((global::System.Drawing.Color)(this["Operator"]));
            }
            set {
                this["Operator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OperatorBold {
            get {
                return ((bool)(this["OperatorBold"]));
            }
            set {
                this["OperatorBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OperatorItalic {
            get {
                return ((bool)(this["OperatorItalic"]));
            }
            set {
                this["OperatorItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("129, 160, 227")]
        public global::System.Drawing.Color PseudoClass {
            get {
                return ((global::System.Drawing.Color)(this["PseudoClass"]));
            }
            set {
                this["PseudoClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PseudoClassBold {
            get {
                return ((bool)(this["PseudoClassBold"]));
            }
            set {
                this["PseudoClassBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PseudoClassItalic {
            get {
                return ((bool)(this["PseudoClassItalic"]));
            }
            set {
                this["PseudoClassItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 161, 195")]
        public global::System.Drawing.Color PseudoElement {
            get {
                return ((global::System.Drawing.Color)(this["PseudoElement"]));
            }
            set {
                this["PseudoElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PseudoElementBold {
            get {
                return ((bool)(this["PseudoElementBold"]));
            }
            set {
                this["PseudoElementBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PseudoElementItalic {
            get {
                return ((bool)(this["PseudoElementItalic"]));
            }
            set {
                this["PseudoElementItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("162, 201, 150")]
        public global::System.Drawing.Color SingleString {
            get {
                return ((global::System.Drawing.Color)(this["SingleString"]));
            }
            set {
                this["SingleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleStringBold {
            get {
                return ((bool)(this["SingleStringBold"]));
            }
            set {
                this["SingleStringBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleStringItalic {
            get {
                return ((bool)(this["SingleStringItalic"]));
            }
            set {
                this["SingleStringItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 161, 195")]
        public global::System.Drawing.Color Tag {
            get {
                return ((global::System.Drawing.Color)(this["Tag"]));
            }
            set {
                this["Tag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TagBold {
            get {
                return ((bool)(this["TagBold"]));
            }
            set {
                this["TagBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TagItalic {
            get {
                return ((bool)(this["TagItalic"]));
            }
            set {
                this["TagItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("236, 98, 104")]
        public global::System.Drawing.Color UnknownIdentifier {
            get {
                return ((global::System.Drawing.Color)(this["UnknownIdentifier"]));
            }
            set {
                this["UnknownIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnknownIdentifierBold {
            get {
                return ((bool)(this["UnknownIdentifierBold"]));
            }
            set {
                this["UnknownIdentifierBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnknownIdentifierItalic {
            get {
                return ((bool)(this["UnknownIdentifierItalic"]));
            }
            set {
                this["UnknownIdentifierItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("236, 98, 104")]
        public global::System.Drawing.Color UnknownPseudoClass {
            get {
                return ((global::System.Drawing.Color)(this["UnknownPseudoClass"]));
            }
            set {
                this["UnknownPseudoClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnknownPseudoClassBold {
            get {
                return ((bool)(this["UnknownPseudoClassBold"]));
            }
            set {
                this["UnknownPseudoClassBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnknownPseudoClassItalic {
            get {
                return ((bool)(this["UnknownPseudoClassItalic"]));
            }
            set {
                this["UnknownPseudoClassItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("249, 176, 99")]
        public global::System.Drawing.Color Value {
            get {
                return ((global::System.Drawing.Color)(this["Value"]));
            }
            set {
                this["Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ValueBold {
            get {
                return ((bool)(this["ValueBold"]));
            }
            set {
                this["ValueBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ValueItalic {
            get {
                return ((bool)(this["ValueItalic"]));
            }
            set {
                this["ValueItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237, 62, 62")]
        public global::System.Drawing.Color Variable {
            get {
                return ((global::System.Drawing.Color)(this["Variable"]));
            }
            set {
                this["Variable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VariableBold {
            get {
                return ((bool)(this["VariableBold"]));
            }
            set {
                this["VariableBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VariableItalic {
            get {
                return ((bool)(this["VariableItalic"]));
            }
            set {
                this["VariableItalic"] = value;
            }
        }
    }
}
