//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netplait.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class JS : global::System.Configuration.ApplicationSettingsBase {
        
        private static JS defaultInstance = ((JS)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new JS())));
        
        public static JS Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Caret {
            get {
                return ((global::System.Drawing.Color)(this["Caret"]));
            }
            set {
                this["Caret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color Defaulttext {
            get {
                return ((global::System.Drawing.Color)(this["Defaulttext"]));
            }
            set {
                this["Defaulttext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaulttextBold {
            get {
                return ((bool)(this["DefaulttextBold"]));
            }
            set {
                this["DefaulttextBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaulttextItalic {
            get {
                return ((bool)(this["DefaulttextItalic"]));
            }
            set {
                this["DefaulttextItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color Comment {
            get {
                return ((global::System.Drawing.Color)(this["Comment"]));
            }
            set {
                this["Comment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentBold {
            get {
                return ((bool)(this["CommentBold"]));
            }
            set {
                this["CommentBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentItalic {
            get {
                return ((bool)(this["CommentItalic"]));
            }
            set {
                this["CommentItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color CommentLine {
            get {
                return ((global::System.Drawing.Color)(this["CommentLine"]));
            }
            set {
                this["CommentLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentLineBold {
            get {
                return ((bool)(this["CommentLineBold"]));
            }
            set {
                this["CommentLineBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentLineItalic {
            get {
                return ((bool)(this["CommentLineItalic"]));
            }
            set {
                this["CommentLineItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color CommentDoc {
            get {
                return ((global::System.Drawing.Color)(this["CommentDoc"]));
            }
            set {
                this["CommentDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentDocBold {
            get {
                return ((bool)(this["CommentDocBold"]));
            }
            set {
                this["CommentDocBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentDocItalic {
            get {
                return ((bool)(this["CommentDocItalic"]));
            }
            set {
                this["CommentDocItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Number {
            get {
                return ((global::System.Drawing.Color)(this["Number"]));
            }
            set {
                this["Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NumberBold {
            get {
                return ((bool)(this["NumberBold"]));
            }
            set {
                this["NumberBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NumberItalic {
            get {
                return ((bool)(this["NumberItalic"]));
            }
            set {
                this["NumberItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color StringEol {
            get {
                return ((global::System.Drawing.Color)(this["StringEol"]));
            }
            set {
                this["StringEol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StringEolBold {
            get {
                return ((bool)(this["StringEolBold"]));
            }
            set {
                this["StringEolBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StringEolItalic {
            get {
                return ((bool)(this["StringEolItalic"]));
            }
            set {
                this["StringEolItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color CommentLineDoc {
            get {
                return ((global::System.Drawing.Color)(this["CommentLineDoc"]));
            }
            set {
                this["CommentLineDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentLineDocBold {
            get {
                return ((bool)(this["CommentLineDocBold"]));
            }
            set {
                this["CommentLineDocBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentLineDocItalic {
            get {
                return ((bool)(this["CommentLineDocItalic"]));
            }
            set {
                this["CommentLineDocItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color CommentDocKeyword {
            get {
                return ((global::System.Drawing.Color)(this["CommentDocKeyword"]));
            }
            set {
                this["CommentDocKeyword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentDocKeywordBold {
            get {
                return ((bool)(this["CommentDocKeywordBold"]));
            }
            set {
                this["CommentDocKeywordBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentDocKeywordItalic {
            get {
                return ((bool)(this["CommentDocKeywordItalic"]));
            }
            set {
                this["CommentDocKeywordItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color CommentDocKeywordError {
            get {
                return ((global::System.Drawing.Color)(this["CommentDocKeywordError"]));
            }
            set {
                this["CommentDocKeywordError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentDocKeywordErrorBold {
            get {
                return ((bool)(this["CommentDocKeywordErrorBold"]));
            }
            set {
                this["CommentDocKeywordErrorBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentDocKeywordErrorItalic {
            get {
                return ((bool)(this["CommentDocKeywordErrorItalic"]));
            }
            set {
                this["CommentDocKeywordErrorItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180, 144, 196")]
        public global::System.Drawing.Color Word {
            get {
                return ((global::System.Drawing.Color)(this["Word"]));
            }
            set {
                this["Word"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WordBold {
            get {
                return ((bool)(this["WordBold"]));
            }
            set {
                this["WordBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WordItalic {
            get {
                return ((bool)(this["WordItalic"]));
            }
            set {
                this["WordItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96, 153, 200")]
        public global::System.Drawing.Color Word2 {
            get {
                return ((global::System.Drawing.Color)(this["Word2"]));
            }
            set {
                this["Word2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Word2Bold {
            get {
                return ((bool)(this["Word2Bold"]));
            }
            set {
                this["Word2Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Word2Italic {
            get {
                return ((bool)(this["Word2Italic"]));
            }
            set {
                this["Word2Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144, 177, 118")]
        public global::System.Drawing.Color String {
            get {
                return ((global::System.Drawing.Color)(this["String"]));
            }
            set {
                this["String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StringBold {
            get {
                return ((bool)(this["StringBold"]));
            }
            set {
                this["StringBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StringItalic {
            get {
                return ((bool)(this["StringItalic"]));
            }
            set {
                this["StringItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144, 177, 118")]
        public global::System.Drawing.Color Character {
            get {
                return ((global::System.Drawing.Color)(this["Character"]));
            }
            set {
                this["Character"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CharacterBold {
            get {
                return ((bool)(this["CharacterBold"]));
            }
            set {
                this["CharacterBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CharacterItalic {
            get {
                return ((bool)(this["CharacterItalic"]));
            }
            set {
                this["CharacterItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("162, 201, 150")]
        public global::System.Drawing.Color UUID {
            get {
                return ((global::System.Drawing.Color)(this["UUID"]));
            }
            set {
                this["UUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UUIDBold {
            get {
                return ((bool)(this["UUIDBold"]));
            }
            set {
                this["UUIDBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UUIDItalic {
            get {
                return ((bool)(this["UUIDItalic"]));
            }
            set {
                this["UUIDItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("129, 160, 227")]
        public global::System.Drawing.Color Operator {
            get {
                return ((global::System.Drawing.Color)(this["Operator"]));
            }
            set {
                this["Operator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OperatorBold {
            get {
                return ((bool)(this["OperatorBold"]));
            }
            set {
                this["OperatorBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Operatoritalic {
            get {
                return ((bool)(this["Operatoritalic"]));
            }
            set {
                this["Operatoritalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("121, 175, 219")]
        public global::System.Drawing.Color Identifier {
            get {
                return ((global::System.Drawing.Color)(this["Identifier"]));
            }
            set {
                this["Identifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdentifierBold {
            get {
                return ((bool)(this["IdentifierBold"]));
            }
            set {
                this["IdentifierBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdentifierItalic {
            get {
                return ((bool)(this["IdentifierItalic"]));
            }
            set {
                this["IdentifierItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("162, 201, 150")]
        public global::System.Drawing.Color Verbatim {
            get {
                return ((global::System.Drawing.Color)(this["Verbatim"]));
            }
            set {
                this["Verbatim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerbatimBold {
            get {
                return ((bool)(this["VerbatimBold"]));
            }
            set {
                this["VerbatimBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerbatimItalic {
            get {
                return ((bool)(this["VerbatimItalic"]));
            }
            set {
                this["VerbatimItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("162, 201, 150")]
        public global::System.Drawing.Color Regex {
            get {
                return ((global::System.Drawing.Color)(this["Regex"]));
            }
            set {
                this["Regex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegexBold {
            get {
                return ((bool)(this["RegexBold"]));
            }
            set {
                this["RegexBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegexItalic {
            get {
                return ((bool)(this["RegexItalic"]));
            }
            set {
                this["RegexItalic"] = value;
            }
        }
    }
}
