//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netplait.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Py : global::System.Configuration.ApplicationSettingsBase {
        
        private static Py defaultInstance = ((Py)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Py())));
        
        public static Py Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Caret {
            get {
                return ((global::System.Drawing.Color)(this["Caret"]));
            }
            set {
                this["Caret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color Defaulttext {
            get {
                return ((global::System.Drawing.Color)(this["Defaulttext"]));
            }
            set {
                this["Defaulttext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultBold {
            get {
                return ((bool)(this["DefaultBold"]));
            }
            set {
                this["DefaultBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultItalic {
            get {
                return ((bool)(this["DefaultItalic"]));
            }
            set {
                this["DefaultItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Numbers {
            get {
                return ((global::System.Drawing.Color)(this["Numbers"]));
            }
            set {
                this["Numbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NumberBold {
            get {
                return ((bool)(this["NumberBold"]));
            }
            set {
                this["NumberBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NumberItalic {
            get {
                return ((bool)(this["NumberItalic"]));
            }
            set {
                this["NumberItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144, 177, 118")]
        public global::System.Drawing.Color Strings {
            get {
                return ((global::System.Drawing.Color)(this["Strings"]));
            }
            set {
                this["Strings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StringBold {
            get {
                return ((bool)(this["StringBold"]));
            }
            set {
                this["StringBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StringItalic {
            get {
                return ((bool)(this["StringItalic"]));
            }
            set {
                this["StringItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144, 177, 118")]
        public global::System.Drawing.Color Characters {
            get {
                return ((global::System.Drawing.Color)(this["Characters"]));
            }
            set {
                this["Characters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CharacterBold {
            get {
                return ((bool)(this["CharacterBold"]));
            }
            set {
                this["CharacterBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CharacterItalic {
            get {
                return ((bool)(this["CharacterItalic"]));
            }
            set {
                this["CharacterItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180, 144, 196")]
        public global::System.Drawing.Color Keywords {
            get {
                return ((global::System.Drawing.Color)(this["Keywords"]));
            }
            set {
                this["Keywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeywordsBold {
            get {
                return ((bool)(this["KeywordsBold"]));
            }
            set {
                this["KeywordsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeywordsItalic {
            get {
                return ((bool)(this["KeywordsItalic"]));
            }
            set {
                this["KeywordsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Classnames {
            get {
                return ((global::System.Drawing.Color)(this["Classnames"]));
            }
            set {
                this["Classnames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClassnamesBold {
            get {
                return ((bool)(this["ClassnamesBold"]));
            }
            set {
                this["ClassnamesBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClassnamesItalic {
            get {
                return ((bool)(this["ClassnamesItalic"]));
            }
            set {
                this["ClassnamesItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 178, 164")]
        public global::System.Drawing.Color Definitionnames {
            get {
                return ((global::System.Drawing.Color)(this["Definitionnames"]));
            }
            set {
                this["Definitionnames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefnameBold {
            get {
                return ((bool)(this["DefnameBold"]));
            }
            set {
                this["DefnameBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefnameItalic {
            get {
                return ((bool)(this["DefnameItalic"]));
            }
            set {
                this["DefnameItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96, 153, 200")]
        public global::System.Drawing.Color Word2 {
            get {
                return ((global::System.Drawing.Color)(this["Word2"]));
            }
            set {
                this["Word2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Word2Bold {
            get {
                return ((bool)(this["Word2Bold"]));
            }
            set {
                this["Word2Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Word2Italic {
            get {
                return ((bool)(this["Word2Italic"]));
            }
            set {
                this["Word2Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 0, 128")]
        public global::System.Drawing.Color Decorators {
            get {
                return ((global::System.Drawing.Color)(this["Decorators"]));
            }
            set {
                this["Decorators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DecoratorsBold {
            get {
                return ((bool)(this["DecoratorsBold"]));
            }
            set {
                this["DecoratorsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DecoratorsItalic {
            get {
                return ((bool)(this["DecoratorsItalic"]));
            }
            set {
                this["DecoratorsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color LineComments {
            get {
                return ((global::System.Drawing.Color)(this["LineComments"]));
            }
            set {
                this["LineComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LineCommentsBold {
            get {
                return ((bool)(this["LineCommentsBold"]));
            }
            set {
                this["LineCommentsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LineCommentsItalic {
            get {
                return ((bool)(this["LineCommentsItalic"]));
            }
            set {
                this["LineCommentsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color TripleComments {
            get {
                return ((global::System.Drawing.Color)(this["TripleComments"]));
            }
            set {
                this["TripleComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TripleCommentsBold {
            get {
                return ((bool)(this["TripleCommentsBold"]));
            }
            set {
                this["TripleCommentsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TripleCommentsItalic {
            get {
                return ((bool)(this["TripleCommentsItalic"]));
            }
            set {
                this["TripleCommentsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color TripleDouble {
            get {
                return ((global::System.Drawing.Color)(this["TripleDouble"]));
            }
            set {
                this["TripleDouble"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TripleDoubleBold {
            get {
                return ((bool)(this["TripleDoubleBold"]));
            }
            set {
                this["TripleDoubleBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TripleDoubleItalic {
            get {
                return ((bool)(this["TripleDoubleItalic"]));
            }
            set {
                this["TripleDoubleItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color Block {
            get {
                return ((global::System.Drawing.Color)(this["Block"]));
            }
            set {
                this["Block"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockBold {
            get {
                return ((bool)(this["BlockBold"]));
            }
            set {
                this["BlockBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockItalic {
            get {
                return ((bool)(this["BlockItalic"]));
            }
            set {
                this["BlockItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color EOL {
            get {
                return ((global::System.Drawing.Color)(this["EOL"]));
            }
            set {
                this["EOL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EOLBold {
            get {
                return ((bool)(this["EOLBold"]));
            }
            set {
                this["EOLBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EOLItalic {
            get {
                return ((bool)(this["EOLItalic"]));
            }
            set {
                this["EOLItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52, 61, 70")]
        public global::System.Drawing.Color BackColorDark {
            get {
                return ((global::System.Drawing.Color)(this["BackColorDark"]));
            }
            set {
                this["BackColorDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("183, 183, 183")]
        public global::System.Drawing.Color ForeColorDark {
            get {
                return ((global::System.Drawing.Color)(this["ForeColorDark"]));
            }
            set {
                this["ForeColorDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BackColorWhite {
            get {
                return ((global::System.Drawing.Color)(this["BackColorWhite"]));
            }
            set {
                this["BackColorWhite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColorWhite {
            get {
                return ((global::System.Drawing.Color)(this["ForeColorWhite"]));
            }
            set {
                this["ForeColorWhite"] = value;
            }
        }
    }
}
