//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netplait.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartPage {
            get {
                return ((bool)(this["StartPage"]));
            }
            set {
                this["StartPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoComplete {
            get {
                return ((bool)(this["AutoComplete"]));
            }
            set {
                this["AutoComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::ScintillaNET.WrapMode WrapMode {
            get {
                return ((global::ScintillaNET.WrapMode)(this["WrapMode"]));
            }
            set {
                this["WrapMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScrollPastLastLine {
            get {
                return ((bool)(this["ScrollPastLastLine"]));
            }
            set {
                this["ScrollPastLastLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LongArrow")]
        public global::ScintillaNET.TabDrawMode TabDrawMode {
            get {
                return ((global::ScintillaNET.TabDrawMode)(this["TabDrawMode"]));
            }
            set {
                this["TabDrawMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Line")]
        public global::ScintillaNET.CaretStyle CaretStyle {
            get {
                return ((global::ScintillaNET.CaretStyle)(this["CaretStyle"]));
            }
            set {
                this["CaretStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int TabWidth {
            get {
                return ((int)(this["TabWidth"]));
            }
            set {
                this["TabWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas")]
        public string GlobalFont {
            get {
                return ((string)(this["GlobalFont"]));
            }
            set {
                this["GlobalFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int GlobalFontSize {
            get {
                return ((int)(this["GlobalFontSize"]));
            }
            set {
                this["GlobalFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MarginWidth {
            get {
                return ((int)(this["MarginWidth"]));
            }
            set {
                this["MarginWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color CaretLineBackColor {
            get {
                return ((global::System.Drawing.Color)(this["CaretLineBackColor"]));
            }
            set {
                this["CaretLineBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaretLineVIsible {
            get {
                return ((bool)(this["CaretLineVIsible"]));
            }
            set {
                this["CaretLineVIsible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CaretWidth {
            get {
                return ((int)(this["CaretWidth"]));
            }
            set {
                this["CaretWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseTabs {
            get {
                return ((bool)(this["UseTabs"]));
            }
            set {
                this["UseTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LcdOptimized")]
        public global::ScintillaNET.FontQuality FontQuality {
            get {
                return ((global::ScintillaNET.FontQuality)(this["FontQuality"]));
            }
            set {
                this["FontQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::ScintillaNET.VirtualSpace VirtualSpaceOptions {
            get {
                return ((global::ScintillaNET.VirtualSpace)(this["VirtualSpaceOptions"]));
            }
            set {
                this["VirtualSpaceOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CrLf")]
        public global::ScintillaNET.Eol EolMode {
            get {
                return ((global::ScintillaNET.Eol)(this["EolMode"]));
            }
            set {
                this["EolMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewEol {
            get {
                return ((bool)(this["ViewEol"]));
            }
            set {
                this["ViewEol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200, 200")]
        public global::System.Drawing.Color SetSelectionBackColor {
            get {
                return ((global::System.Drawing.Color)(this["SetSelectionBackColor"]));
            }
            set {
                this["SetSelectionBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HighlightLine {
            get {
                return ((bool)(this["HighlightLine"]));
            }
            set {
                this["HighlightLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayLineNumber {
            get {
                return ((bool)(this["DisplayLineNumber"]));
            }
            set {
                this["DisplayLineNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invisible")]
        public global::ScintillaNET.WhitespaceMode IndentationGuides {
            get {
                return ((global::ScintillaNET.WhitespaceMode)(this["IndentationGuides"]));
            }
            set {
                this["IndentationGuides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color CaretForeColor {
            get {
                return ((global::System.Drawing.Color)(this["CaretForeColor"]));
            }
            set {
                this["CaretForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PythonContents {
            get {
                return ((string)(this["PythonContents"]));
            }
            set {
                this["PythonContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HTMLContents {
            get {
                return ((string)(this["HTMLContents"]));
            }
            set {
                this["HTMLContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CSSContents {
            get {
                return ((string)(this["CSSContents"]));
            }
            set {
                this["CSSContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JSContents {
            get {
                return ((string)(this["JSContents"]));
            }
            set {
                this["JSContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SQLContents {
            get {
                return ((string)(this["SQLContents"]));
            }
            set {
                this["SQLContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBrackets {
            get {
                return ((bool)(this["ShowBrackets"]));
            }
            set {
                this["ShowBrackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCurlyBrackets {
            get {
                return ((bool)(this["ShowCurlyBrackets"]));
            }
            set {
                this["ShowCurlyBrackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSquareBrackets {
            get {
                return ((bool)(this["ShowSquareBrackets"]));
            }
            set {
                this["ShowSquareBrackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAngleBrackets {
            get {
                return ((bool)(this["ShowAngleBrackets"]));
            }
            set {
                this["ShowAngleBrackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowQuotes {
            get {
                return ((bool)(this["ShowQuotes"]));
            }
            set {
                this["ShowQuotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSingleQuote {
            get {
                return ((bool)(this["ShowSingleQuote"]));
            }
            set {
                this["ShowSingleQuote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("226, 230, 214")]
        public global::System.Drawing.Color BraceLightBack {
            get {
                return ((global::System.Drawing.Color)(this["BraceLightBack"]));
            }
            set {
                this["BraceLightBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color BraceLightFore {
            get {
                return ((global::System.Drawing.Color)(this["BraceLightFore"]));
            }
            set {
                this["BraceLightFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int NumberMarginWidth {
            get {
                return ((int)(this["NumberMarginWidth"]));
            }
            set {
                this["NumberMarginWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int BookmarkMarginWidth {
            get {
                return ((int)(this["BookmarkMarginWidth"]));
            }
            set {
                this["BookmarkMarginWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DarkTheme {
            get {
                return ((bool)(this["DarkTheme"]));
            }
            set {
                this["DarkTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("194, 196, 188")]
        public global::System.Drawing.Color BraceDarkBack {
            get {
                return ((global::System.Drawing.Color)(this["BraceDarkBack"]));
            }
            set {
                this["BraceDarkBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color BraceDarkFore {
            get {
                return ((global::System.Drawing.Color)(this["BraceDarkFore"]));
            }
            set {
                this["BraceDarkFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkspaceCollapsed {
            get {
                return ((bool)(this["WorkspaceCollapsed"]));
            }
            set {
                this["WorkspaceCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForPath {
            get {
                return ((bool)(this["CheckForPath"]));
            }
            set {
                this["CheckForPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PythonPath {
            get {
                return ((string)(this["PythonPath"]));
            }
            set {
                this["PythonPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K py -i \"($FILENAME)\"")]
        public string PythonRunArgs {
            get {
                return ((string)(this["PythonRunArgs"]));
            }
            set {
                this["PythonRunArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CMD.exe")]
        public string PythonRunWith {
            get {
                return ((string)(this["PythonRunWith"]));
            }
            set {
                this["PythonRunWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RightToLeft {
            get {
                return ((bool)(this["RightToLeft"]));
            }
            set {
                this["RightToLeft"] = value;
            }
        }
    }
}
